# This is a basic workflow to help you get started with Actions

name: Deploy release to Maven Central

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java with importing GPG
        uses: actions/setup-java@v2
        with: # running setup-java again overwrites the settings.xml
          java-version: '16'
          distribution: 'adopt'
          server-id: ossrh 
          server-username: MAVEN_USERNAME
          server-password: MAVEN_USER_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} 

      - name: Deploy
        run: |
          mvn clean deploy --batch-mode --no-transfer-progress -DskipTests=true -Dchangelist= -Drevision=${{ github.event.release.name }} -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}
        working-directory: logback-newrelic-appender
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_USER_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
